
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-sa
secrets:
- name: git-credential-basic

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: trigger-sa


---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-build
secrets:
  - name: docker-credentials


