apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: tekton-sample-python-el
spec:
  # resources:
  #   kubernetesResource:
  #     serviceType: LoadBalancer
  serviceAccountName: trigger-sa
  triggers:
    - name: tekton-trigger
      bindings:
       - ref: tekton-sample-python-tb
      template:
         ref: tekton-sample-python-tt