apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: tekton-sample-python-pipe-run- 
spec:
  serviceAccountName: tekton-build 
  pipelineRef: 
    name: tekton-sample-python-pipe
  podTemplate:
    securityContext:  
      fsGroup: 65532 
  workspaces: 
  - name: shared-data
    volumeClaimTemplate: 
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  - name: docker-credentials
    secret:
      secretName: docker-credentials

  params: 
  - name: repo-url
    value: "https://github.com/oebinu/tekton-sample-python.git"
  - name: image-reference
    value: cocopopo/sample-py:v3
  - name: kubectl-args
    value:
      - "apply"
      - "-f"
      - "./6th_trigger/10_k8s_trigger.yaml"